### ISSUE TITLE
JD上面的怎么跳过分享？

### ISSUE THREAD

**Issue by changer2222** [youyi-sizuru/AutoCat#5]
rt，它上面也是已完成这个。
还有你这几个图是哪几个页面出来的？5个货物加购物我重新截图，还是不行

**Comment by youyi-sizuru** [comment]
> rt，它上面也是已完成这个。 还有你这几个图是哪几个页面出来的？5个货物加购物我重新截图，还是不行

京东我做的不太好，你可以去找找其他人的，有用WebDivider实现的，识别图片确实适配性太烂了。

**Comment by changer2222** [comment]
没事了，我自己后来多跑了两次，找到合适的图了，现在跑的还不错
有使用Webdivider跑的地址是哪个，推荐看下。

**Comment by youyi-sizuru** [comment]
> 没事了，我自己后来多跑了两次，找到合适的图了，现在跑的还不错 有使用Webdivider跑的地址是哪个，推荐看下。

https://github.com/testerzhang/jd_pc_auto_practise
可以看看这个人的，应该比我的好用
